name = "Spiders"
uuid = "52854307-bbd1-4ac7-933f-adc0936abe8a"
authors = ["Jeffrey Wack"]
version = "0.1.0"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
Primes = "0.5"
GLMakie = "0.10"
PkgTemplates = "0.7"
ColorSchemes = "3"
IterTools = "1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
